// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bills.sql

package sqlc

import (
	"context"
)

const createBill = `-- name: CreateBill :one
INSERT INTO bills (name, amount, due_day) VALUES (?, ?, ?) RETURNING id, name, amount, due_day
`

type CreateBillParams struct {
	Name   string `json:"name"`
	Amount int64  `json:"amount"`
	DueDay int64  `json:"dueDay"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRowContext(ctx, createBill, arg.Name, arg.Amount, arg.DueDay)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.DueDay,
	)
	return i, err
}

const deleteBill = `-- name: DeleteBill :exec
DELETE FROM bills WHERE id = ?
`

func (q *Queries) DeleteBill(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBill, id)
	return err
}

const getAllBills = `-- name: GetAllBills :many
SELECT id, name, amount, due_day FROM bills ORDER BY due_day, id
`

func (q *Queries) GetAllBills(ctx context.Context) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, getAllBills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bill{}
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.DueDay,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBill = `-- name: UpdateBill :exec
UPDATE bills SET name = ?, amount = ?, due_day = ? WHERE id = ?
`

type UpdateBillParams struct {
	Name   string `json:"name"`
	Amount int64  `json:"amount"`
	DueDay int64  `json:"dueDay"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) error {
	_, err := q.db.ExecContext(ctx, updateBill,
		arg.Name,
		arg.Amount,
		arg.DueDay,
		arg.ID,
	)
	return err
}
