// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"
)

const addCategory = `-- name: AddCategory :exec
INSERT OR IGNORE INTO categories (type, name) VALUES (?, ?)
`

type AddCategoryParams struct {
	Type string `json:"type"`
	Name string `json:"name"`
}

func (q *Queries) AddCategory(ctx context.Context, arg AddCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addCategory, arg.Type, arg.Name)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE type = ? AND name = ?
`

type DeleteCategoryParams struct {
	Type string `json:"type"`
	Name string `json:"name"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.Type, arg.Name)
	return err
}

const getCategoriesByType = `-- name: GetCategoriesByType :many
SELECT name FROM categories WHERE type = ? ORDER BY id
`

func (q *Queries) GetCategoriesByType(ctx context.Context, type_ string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCategory = `-- name: RenameCategory :exec
UPDATE categories SET name = ? WHERE type = ? AND name = ?
`

type RenameCategoryParams struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Name_2 string `json:"name2"`
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) error {
	_, err := q.db.ExecContext(ctx, renameCategory, arg.Name, arg.Type, arg.Name_2)
	return err
}

const renameCategoryInTransactions = `-- name: RenameCategoryInTransactions :exec
UPDATE transactions SET category = ? WHERE category = ?
`

type RenameCategoryInTransactionsParams struct {
	Category   string `json:"category"`
	Category_2 string `json:"category2"`
}

func (q *Queries) RenameCategoryInTransactions(ctx context.Context, arg RenameCategoryInTransactionsParams) error {
	_, err := q.db.ExecContext(ctx, renameCategoryInTransactions, arg.Category, arg.Category_2)
	return err
}
