// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debts.sql

package sqlc

import (
	"context"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (name) VALUES (?) RETURNING id, name, amount, notes
`

func (q *Queries) CreateDebt(ctx context.Context, name string) (Debt, error) {
	row := q.db.QueryRowContext(ctx, createDebt, name)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Amount,
		&i.Notes,
	)
	return i, err
}

const createInstallment = `-- name: CreateInstallment :exec
INSERT INTO installments (debt_id, due_date, amount, status, paid_date)
VALUES (?, ?, ?, ?, ?)
`

type CreateInstallmentParams struct {
	DebtID   int64  `json:"debtId"`
	DueDate  string `json:"dueDate"`
	Amount   int64  `json:"amount"`
	Status   string `json:"status"`
	PaidDate string `json:"paidDate"`
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) error {
	_, err := q.db.ExecContext(ctx, createInstallment,
		arg.DebtID,
		arg.DueDate,
		arg.Amount,
		arg.Status,
		arg.PaidDate,
	)
	return err
}

const deleteDebt = `-- name: DeleteDebt :exec
DELETE FROM debts WHERE id = ?
`

func (q *Queries) DeleteDebt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDebt, id)
	return err
}

const deleteInstallmentsByDebt = `-- name: DeleteInstallmentsByDebt :exec
DELETE FROM installments WHERE debt_id = ?
`

func (q *Queries) DeleteInstallmentsByDebt(ctx context.Context, debtID int64) error {
	_, err := q.db.ExecContext(ctx, deleteInstallmentsByDebt, debtID)
	return err
}

const getAllDebts = `-- name: GetAllDebts :many
SELECT id, name, amount, notes FROM debts ORDER BY id
`

func (q *Queries) GetAllDebts(ctx context.Context) ([]Debt, error) {
	rows, err := q.db.QueryContext(ctx, getAllDebts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debt{}
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstallmentsByDebt = `-- name: GetInstallmentsByDebt :many
SELECT id, debt_id, due_date, amount, status, paid_date
FROM installments WHERE debt_id = ? ORDER BY due_date, id
`

func (q *Queries) GetInstallmentsByDebt(ctx context.Context, debtID int64) ([]Installment, error) {
	rows, err := q.db.QueryContext(ctx, getInstallmentsByDebt, debtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Installment{}
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.PaidDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebt = `-- name: UpdateDebt :exec
UPDATE debts SET name = ?, amount = ?, notes = ? WHERE id = ?
`

type UpdateDebtParams struct {
	Name   string `json:"name"`
	Amount int64  `json:"amount"`
	Notes  string `json:"notes"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateDebt(ctx context.Context, arg UpdateDebtParams) error {
	_, err := q.db.ExecContext(ctx, updateDebt,
		arg.Name,
		arg.Amount,
		arg.Notes,
		arg.ID,
	)
	return err
}
