// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Account struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Type    string `json:"type"`
	Balance int64  `json:"balance"`
}

type Bill struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Amount int64  `json:"amount"`
	DueDay int64  `json:"dueDay"`
}

type Category struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
	Name string `json:"name"`
}

type Debt struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Amount int64  `json:"amount"`
	Notes  string `json:"notes"`
}

type Installment struct {
	ID       int64  `json:"id"`
	DebtID   int64  `json:"debtId"`
	DueDate  string `json:"dueDate"`
	Amount   int64  `json:"amount"`
	Status   string `json:"status"`
	PaidDate string `json:"paidDate"`
}

type Transaction struct {
	ID        int64  `json:"id"`
	AccountID int64  `json:"accountId"`
	Date      string `json:"date"`
	Name      string `json:"name"`
	Amount    int64  `json:"amount"`
	Category  string `json:"category"`
	Notes     string `json:"notes"`
}
