// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (account_id, date, name, amount, category, notes)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, account_id, date, name, amount, category, notes
`

type CreateTransactionParams struct {
	AccountID int64  `json:"accountId"`
	Date      string `json:"date"`
	Name      string `json:"name"`
	Amount    int64  `json:"amount"`
	Category  string `json:"category"`
	Notes     string `json:"notes"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.AccountID,
		arg.Date,
		arg.Name,
		arg.Amount,
		arg.Category,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Date,
		&i.Name,
		&i.Amount,
		&i.Category,
		&i.Notes,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getTransactionAccountID = `-- name: GetTransactionAccountID :one
SELECT account_id FROM transactions WHERE id = ?
`

func (q *Queries) GetTransactionAccountID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTransactionAccountID, id)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}

const getTransactionsByAccount = `-- name: GetTransactionsByAccount :many
SELECT id, account_id, date, name, amount, category, notes
FROM transactions WHERE account_id = ? ORDER BY date DESC, id DESC
`

func (q *Queries) GetTransactionsByAccount(ctx context.Context, accountID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Name,
			&i.Amount,
			&i.Category,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalcAccountBalance = `-- name: RecalcAccountBalance :exec
UPDATE accounts SET balance = COALESCE(
    (SELECT SUM(amount) FROM transactions WHERE transactions.account_id = ?), 0
) WHERE accounts.id = ?
`

type RecalcAccountBalanceParams struct {
	AccountID int64 `json:"accountId"`
	ID        int64 `json:"id"`
}

func (q *Queries) RecalcAccountBalance(ctx context.Context, arg RecalcAccountBalanceParams) error {
	_, err := q.db.ExecContext(ctx, recalcAccountBalance, arg.AccountID, arg.ID)
	return err
}
