// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {transaction} from '../models';

export function AddCategory(arg1:string,arg2:string):Promise<void>;

export function CreateAccount(arg1:string,arg2:string,arg3:number):Promise<account.AccountData>;

export function CreateTransaction(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<transaction.TransactionData>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteCategory(arg1:string,arg2:string):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetAccounts():Promise<Array<account.AccountData>>;

export function GetCategories(arg1:string):Promise<Array<string>>;

export function GetTransactions(arg1:number):Promise<Array<transaction.TransactionData>>;

export function RenameCategory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateAccount(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;
