// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1, arg2) {
  return window['go']['main']['App']['AddCategory'](arg1, arg2);
}

export function CreateAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3);
}

export function CreateTransaction(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateTransaction'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteCategory(arg1, arg2) {
  return window['go']['main']['App']['DeleteCategory'](arg1, arg2);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetCategories(arg1) {
  return window['go']['main']['App']['GetCategories'](arg1);
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function RenameCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2, arg3);
}

export function UpdateAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3, arg4);
}
